### ISSUE TITLE
Not able to install with the setup.py/ez_setup.py

### ISSUE THREAD

**Issue by s3luX** [adafruit/Adafruit_Python_LED_Backpack#27]
Hello I have issues installing the libraries with the setup.py and ez_setup.py scripts. I have installed all the necessary dependencies that were documented in the readme but I`m still unable to install the LED Backpack:

root@TEST-RPi:/home/pi/Adafruit_Python_LED_Backpack# **apt-get install build-essential python-dev python-smbus python-imaging git**
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
git is already the newest version (1:2.11.0-3+deb9u3).
python-dev is already the newest version (2.7.13-2).
python-imaging is already the newest version (4.0.0-4).
python-smbus is already the newest version (3.1.2-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@TEST-RPi:/home/pi/Adafruit_Python_LED_Backpack# **python setup.py install**
Extracting in /tmp/tmpedyF2X
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    use_setuptools()
  File "/home/pi/Adafruit_Python_LED_Backpack/ez_setup.py", line 128, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pi/Adafruit_Python_LED_Backpack/ez_setup.py", line 108, in _do_download
    _build_egg(egg, archive, to_dir)
  File "/home/pi/Adafruit_Python_LED_Backpack/ez_setup.py", line 57, in _build_egg
    with archive_context(archive_filename):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/pi/Adafruit_Python_LED_Backpack/ez_setup.py", line 88, in archive_context
    with get_zip_class()(filename) as archive:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
root@TEST-RPi:/home/pi/Adafruit_Python_LED_Backpack# **python ez_setup.py install**
Extracting in /tmp/tmpFQnNJI
Traceback (most recent call last):
  File "ez_setup.py", line 332, in <module>
    sys.exit(main())
  File "ez_setup.py", line 329, in main
    return _install(archive, _build_install_args(options))
  File "ez_setup.py", line 46, in _install
    with archive_context(archive_filename):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "ez_setup.py", line 88, in archive_context
    with get_zip_class()(filename) as archive:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
root@TEST-RPi:/home/pi/Adafruit_Python_LED_Backpack#

I`m running the latest version of Raspbian on the Rpi, all dependencies are up to date.

Can you help me?

Thank you in advance!

**Comment by ladyada** [comment]
hi we're actuallt going to discontinue this older python library, could you try the circuitpython library? its nearly identical and you can install everything thru pypi :)

how to install raspi support
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33/releases
examples:
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33/tree/master/examples
