### ISSUE TITLE
Problems on RPi

### ISSUE THREAD

**Issue by xamgreen** [adafruit/Adafruit_Python_LED_Backpack#3]
Hey,

i got problems getting it running on raspberrypi. It writes "No File or Directory". i also cant get the "Image" module running. I removed that from the scripts.

here are my outputs:
```
pi@RPI02 ~ $ wget https://github.com/adafruit/Adafruit_Python_LED_Backpack/archive/master.zip
--2015-07-25 10:30:25--  https://github.com/adafruit/Adafruit_Python_LED_Backpack/archive/master.zip
Resolving github.com (github.com)... 192.30.252.130
Connecting to github.com (github.com)|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/adafruit/Adafruit_Python_LED_Backpack/zip/master [following]
--2015-07-25 10:30:32--  https://codeload.github.com/adafruit/Adafruit_Python_LED_Backpack/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.252.145
Connecting to codeload.github.com (codeload.github.com)|192.30.252.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: `master.zip'

    [ <=>                                                                                                                                                     ] 26,231      --.-K/s   in 0.1s    

2015-07-25 10:30:36 (190 KB/s) - `master.zip' saved [26231]


pi@RPI02 ~ $ unzip -a master.zip
Archive:  master.zip
a6da0e5130ae23d5f50d0a22a9cb2a56ecc31298
   creating: Adafruit_Python_LED_Backpack-master/
 extracting: Adafruit_Python_LED_Backpack-master/.gitignore  [text]  
   creating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/
  inflating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/AlphaNum4.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/BicolorBargraph24.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/BicolorMatrix8x8.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/HT16K33.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/Matrix8x8.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/SevenSegment.py  [text]  
 extracting: Adafruit_Python_LED_Backpack-master/Adafruit_LED_Backpack/__init__.py  [empty] 
  inflating: Adafruit_Python_LED_Backpack-master/LICENSE  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/README.md  [text]  
   creating: Adafruit_Python_LED_Backpack-master/examples/
  inflating: Adafruit_Python_LED_Backpack-master/examples/alphanum4_test.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/examples/bicolor_bargraph24_test.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/examples/bicolor_matrix8x8_test.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/examples/matrix8x8_test.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/examples/sevensegment_test.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/ez_setup.py  [text]  
  inflating: Adafruit_Python_LED_Backpack-master/setup.py  [text]  


pi@RPI02 ~ $ cd Adafruit_Python_LED_Backpack-master/


pi@RPI02 ~/Adafruit_Python_LED_Backpack-master $ sudo python setup.py install 
running install
running bdist_egg
running egg_info
creating Adafruit_LED_Backpack.egg-info
writing requirements to Adafruit_LED_Backpack.egg-info/requires.txt
writing Adafruit_LED_Backpack.egg-info/PKG-INFO
writing top-level names to Adafruit_LED_Backpack.egg-info/top_level.txt
writing dependency_links to Adafruit_LED_Backpack.egg-info/dependency_links.txt
writing manifest file 'Adafruit_LED_Backpack.egg-info/SOURCES.txt'
reading manifest file 'Adafruit_LED_Backpack.egg-info/SOURCES.txt'
writing manifest file 'Adafruit_LED_Backpack.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/BicolorBargraph24.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/HT16K33.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/SevenSegment.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/__init__.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/AlphaNum4.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/Matrix8x8.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
copying Adafruit_LED_Backpack/BicolorMatrix8x8.py -> build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/BicolorBargraph24.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/HT16K33.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/SevenSegment.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/__init__.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/AlphaNum4.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/Matrix8x8.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
copying build/lib.linux-armv7l-2.7/Adafruit_LED_Backpack/BicolorMatrix8x8.py -> build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/BicolorBargraph24.py to BicolorBargraph24.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/HT16K33.py to HT16K33.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/SevenSegment.py to SevenSegment.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/AlphaNum4.py to AlphaNum4.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/Matrix8x8.py to Matrix8x8.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/BicolorMatrix8x8.py to BicolorMatrix8x8.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_LED_Backpack.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_LED_Backpack.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_LED_Backpack.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_LED_Backpack.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_LED_Backpack.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/Adafruit_LED_Backpack-1.5.0-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing Adafruit_LED_Backpack-1.5.0-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/Adafruit_LED_Backpack-1.5.0-py2.7.egg
Copying Adafruit_LED_Backpack-1.5.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adafruit-LED-Backpack 1.5.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/Adafruit_LED_Backpack-1.5.0-py2.7.egg
Processing dependencies for Adafruit-LED-Backpack==1.5.0
Searching for Adafruit-GPIO==0.9.3
Best match: Adafruit-GPIO 0.9.3
Processing Adafruit_GPIO-0.9.3-py2.7.egg
Adafruit-GPIO 0.9.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/Adafruit_GPIO-0.9.3-py2.7.egg
Searching for spidev==3.0
Best match: spidev 3.0
Processing spidev-3.0-py2.7-linux-armv7l.egg
spidev 3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/spidev-3.0-py2.7-linux-armv7l.egg
Finished processing dependencies for Adafruit-LED-Backpack==1.5.0


pi@RPI02 ~/Adafruit_Python_LED_Backpack-master $ python examples/bicolor_matrix8x8_test.py 
Traceback (most recent call last):
  File "examples/bicolor_matrix8x8_test.py", line 30, in <module>
    display = BicolorMatrix8x8.BicolorMatrix8x8()
  File "build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/BicolorMatrix8x8.py", line 40, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_LED_Backpack/HT16K33.py", line 46, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 66, in get_i2c_device
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 95, in __init__
IOError: [Errno 2] No such file or directory


pi@RPI02 ~/Adafruit_Python_LED_Backpack-master $ python --version
Python 2.7.3
```

Would be awesome if someone can help me. :)

**Comment by xamgreen** [comment]
```
pi@RPI02 ~/Adafruit_Python_LED_Backpack-master $ cd build/bdist.linux-armv7l/
pi@RPI02 ~/Adafruit_Python_LED_Backpack-master/build/bdist.linux-armv7l $ ls
```

directory is empty

**Comment by tdicola** [comment]
Ah it looks like it can't find any /dev/i2c* devices--double check I2C is enabled on the Raspberry Pi.  Check this page for details on the kernel module to enable: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c  In particular run raspi-config to enable the I2C device tree parameter, then manually edit /etc/modules to make sure the right I2C drivers are loaded, and finally use the i2cdetect command to double check you can see a device on the I2C bus.  Give that a shot and let me know if you still see issues, thanks!

**Comment by xamgreen** [comment]
Well, Thanks tdicola! The links helps me a lot. I got it working. ;)
